name: Generate Synthetic Dataset

description: Generate synthetic data and embeddings using Makefile targets

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Generate synthetic data
      working-directory: mk
      shell: bash
      run: make -f data.mk generate_synthetic_data

    - name: Generate embeddings
      shell: bash
      run: make -f mk/embeddings.mk generate
