name: Notify Discord on PR Merge to Dev

on:
  pull_request_target:
    types:
      - closed          # fires when PR is closed
    branches:
      - dev             # …and its base branch is dev

jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Build JSON safely
      - name: Build JSON payload
        id: build
        env:
          PR_NUM: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          AUTHOR: ${{ github.event.pull_request.merged_by.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          msg="🔔 FastLanes update:\n**PR #${PR_NUM} – ${PR_TITLE}** was merged into dev by ${AUTHOR}.\n🔗 ${PR_URL}\n\n**PR description:**\n${PR_BODY}"
          payload=$(jq -Rn --arg content "$msg" '{content:$content}')
          echo "json=$payload" >> "$GITHUB_OUTPUT"

      # 2️⃣ Post to Discord
      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "${{ steps.build.outputs.json }}" \
               "${{ secrets.DISCORD_WEBHOOK_URL }}"
