# .github/workflows/notify-dev-push.yml
name: Notify Discord on Push to Dev

on:
  push:
    branches:
      - dev

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"🔔 **FastLanes update:** New commit pushed to \\\`dev\\\` by \\\`${{ github.actor }}\\\`.\\n🔗 https://github.com/${{ github.repository }}/commit/${{ github.sha }}\"}" \
               "${{ secrets.DISCORD_WEBHOOK_URL }}"
